name       : unrar
version    : 5.7.2
release    : 13
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.7.2.tar.gz : 46dd410ba57652e972a6c601e7500d01d0ca3257661577466c2cbf6f843cb13a
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
