name       : unrar
version    : 5.7.4
release    : 15
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.7.4.tar.gz : 582dd038fd4632f32493928cae5b37dbb436752813da08a1ee5df2ab1ee7e7b4
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
