name       : unrar
version    : 5.9.1
release    : 22
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.9.1.tar.gz : 0eb1d1b8e02102fccae775a6d6b79336b69e2cf90e2045de92594dcfb58de100
license    : Distributable
homepage   : https://www.rarlab.com
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
