name       : unrar
version    : 6.2.1
release    : 33
source     :
    - https://www.rarlab.com/rar/unrarsrc-6.2.1.tar.gz : 5cc8f7ded262d27c29d01e7a119d2fd23edda427711820454f2eb667044a8900
homepage   : https://www.rarlab.com
license    : Distributable
component  : system.utils
summary    : RAR decompression program
description: |
    RAR decompression program
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
