name       : unrar
version    : 6.0.4
release    : 26
source     :
    - https://www.rarlab.com/rar/unrarsrc-6.0.4.tar.gz : 130197e495d6e2c2ee790a5beee123edeed642508be13f0159672e5397aca6c1
license    : Distributable
homepage   : https://www.rarlab.com
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
