name       : unrar
version    : 6.2.3
release    : 34
source     :
    - https://www.rarlab.com/rar/unrarsrc-6.2.3.tar.gz : 120936e41f826cd63d77a580aeea64c1b79fd3e2434f58ce8184e783b51e5b01
homepage   : https://www.rarlab.com
license    : Distributable
component  : system.utils
summary    : RAR decompression program
description: |
    RAR decompression program
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
