name       : unrar
version    : 5.8.3
release    : 19
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.8.3.tar.gz : 3591685c8f5bbcb0be09de3d0a0544adb88966b9cccb80986f6cd2b534fd91a6
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
