name       : unrar
version    : 5.6.1
release    : 6
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.6.1.tar.gz : 67c339dffa95f6c1bedcca40045e99de5852919dbfaa06e4a9c8f18cd5064e70
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -D -m 00755 unrar $installdir/usr/bin/unrar
    install -D -m 00644 license.txt $installdir/usr/share/doc/unrar/license.txt
