name       : unrar
version    : 5.3.8
release    : 2
source     :
    - http://www.rarlab.com/rar/unrarsrc-5.3.8.tar.gz : 52386ee592150f009a5438829dffc91c1e0006935e8ef701f3c8d8785b8eeb99
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
build      : |
    %make -f makefile
install    : |
    install -D -m 00755 unrar $installdir/usr/bin/unrar
    install -D -m 00644 license.txt $installdir/usr/share/doc/unrar/license.txt
