name       : unrar
version    : 5.6.5
release    : 9
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.6.5.tar.gz : eba36a421bf41491818dee9507d934064622bc0bd9db6bbb8422a4706f200898
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -D -m 00755 unrar $installdir/usr/bin/unrar
    install -D -m 00644 license.txt $installdir/usr/share/doc/unrar/license.txt
