name       : unrar
version    : 6.1.4
release    : 28
source     :
    - https://www.rarlab.com/rar/unrarsrc-6.1.4.tar.gz : c0ed58629243961c3f1ec90c08b11ff93261e568dbfdce2bf3b759ee7a4a3b7c
license    : Distributable
homepage   : https://www.rarlab.com
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
