name       : unrar
version    : 5.2.7
release    : 1
source     :
    - http://www.rarlab.com/rar/unrarsrc-5.2.7.tar.gz : ef14757e943787b439fedf2c564c1f38d0db315528a928e0de170860717e2fac
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
build      : |
    %make -f makefile
install    : |
    install -D -m 00755 unrar $installdir/usr/bin/unrar
    install -D -m 00644 license.txt $installdir/usr/share/doc/unrar/license.txt
