name       : unrar
version    : 6.1.5
release    : 29
source     :
    - https://www.rarlab.com/rar/unrarsrc-6.1.5.tar.gz : 4e56717d867cdff7a0008b7f1da6aa79ac7a8f974cf134d49a8c16b577bced4a
license    : Distributable
homepage   : https://www.rarlab.com
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
