name       : unrar
version    : 5.6.2
release    : 7
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.6.2.tar.gz : ce048094764b2377dd60802359c74f03528b6d7defd808cd584443c5fd2de948
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -D -m 00755 unrar $installdir/usr/bin/unrar
    install -D -m 00644 license.txt $installdir/usr/share/doc/unrar/license.txt
