name       : unrar
version    : 5.9.2
release    : 23
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz : 73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6
license    : Distributable
homepage   : https://www.rarlab.com
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
