name       : unrar
version    : 6.1.6
release    : 30
source     :
    - https://www.rarlab.com/rar/unrarsrc-6.1.6.tar.gz : 67f4ab891c062218c2badfaac9c8cab5c8bfd5e96dabfca56c8faa3d209a801d
license    : Distributable
homepage   : https://www.rarlab.com
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
