name       : unrar
version    : 5.8.4
release    : 20
source     :
    - https://www.rarlab.com/rar/unrarsrc-5.8.4.tar.gz : 0b7cb2307ef7e65f631496376ce2fdf98b9b0f2136dc4467408ef63f3bf92f96
license    : Distributable
summary    : RAR decompression program
description: |
    RAR decompression program
component  : system.utils
build      : |
    %make -f makefile
install    : |
    install -Dm00755 unrar $installdir/usr/bin/unrar
    install -Dm00644 license.txt $installdir/usr/share/doc/unrar/license.txt
